#+OPTIONS: toc:nil
#+begin_src yaml :exports results :results value html
---
title: "Winter (term) is Coming"
date: "<2020-01-04 Sat>"
---
#+end_src

With winter term approaching, I thought I'd write out some thoughts on the
previous term and my plan going forward.

* Reflecting on Fall Term
  Fall term was my first term in university, and after completing it I feel like
  I have a much better idea of what I need to do to optimize my university
  experience.

  For the first couple of weeks or so of fall I burned myself out trying to
  constantly do school work, because that's what I thought I had to do.
  Following that, when I noticed that I had quite a bit of free time, I
  over-corrected a little and started spending too much time doing personal
  work. As a consequence of this, my grades dropped and my lack of solid study
  material created unneeded stress for me when finals came around.

  Another thing that I noticed was that I was overconfident (sometimes even
  cocky) about exams. I didn't appreciate the difference between doing a
  complicated problem in the comfort of my room with plenty of time and doing
  one in a timed exam worth a significant portion of my grade. Given my attitude
  towards tests, I feel like I was lucky to get away with the grades I did this
  semester.

* Plan for Winter Term
  Given my experience in the fall term, my overall goals for the winter term are
  to:
  1. Allocate time towards personal and school activities in a more balanced
     manner.
     - Ideally, this means doing enough school work to achieve the grades I
       want while still allowing myself enough time to enjoy myself.
     - In order to achieve this goal, I plan to maintain a fairly strict routine
       (wish me luck) where I spend a minimum of 25 minutes on each subject each
       day, in addition to classes. 25 minutes because that is what I have found
       to work best for me when using the Pomodoro method, and I plan to use this
       method for this work. Minimum of 25 because I expect I will need to spend
       more time on some courses than others on different days. This minimum may
       change depending on how I feel about my workload and performance, but I
       think if I can maintain a routine such as this I will be able to achieve
       my desired grades.
     - I think my biggest enemy in achieving this goal will be my habit of
       distracting myself with minor optimizations. For example, I might notice
       while I'm working that a snippet I'm using isn't indenting properly then
       spend the next 15 to 30 minutes figuring out how to fix that. This is a
       bad habit because context switching is very harmful to productivity, and
       switching contexts for something that I could easily live with is just
       silly. So, to avoid this I plan to use ~org-capture~ (a system to quickly
       take notes with minimal context switching) to satiate my impulse to fix
       everything while I'm working, then come back to it once I'm finished. So
       in the previous example, I would ~org-capture~ the problem of the
       incorrectly indented snippet, then forget about it until a time that I
       have set specifically to work on those minor things.
     - An important aspect of the above mentioned routine is that if I meet the
       minimum time I have set for myself in each of the courses, and there is
       no pressing school work to do, I will then allocate personal time. I'm
       not as worried about over-working as under-working, but this condition
       should prevent it.
  2. Maintain a healthy respect for the difficulty of the examinations I will
     take.
     - This doesn't mean fear them and worry about them, just that I aim to make
       a greater effort to understand what they will contain and adjust my
       studying accordingly.
