projects:
    gatsby:
        schema: 'schema.graphql'
        documents: 'src/**/*.{graphql,js,ts,jsx,tsx'
        extensions:
            endpoints:
                default:
                    url: http://localhost:8000/___graphql
