schema: 'schema.graphql'
documents:
    - ./src/**/*.{js,jsx,ts,tsx}
    - ./gatsby-node.ts
projects:
    gatsby:
        extensions:
            endpoints:
                default:
                    url: http://localhost:8000/___graphql
