yarnPath: '.yarn/releases/yarn-berry.cjs'
packageExtensions:
    'autoprefixer@*':
        dependencies:
            postcss: '*'
    'postcss-loader@*':
        dependencies:
            postcss: '*'
    'gatsby-plugin-react-svg@*':
        dependencies:
            svg-react-loader: '*'
